# a10-mostiu/frontend/Dockerfile

# Use an official nginx runtime as a parent image
FROM nginx:alpine

# Copy the static files to the nginx html directory
COPY ./src /usr/share/nginx/html

# Expose the port the app runs on
EXPOSE 80
