# a10-mostiu/docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - tictactoe-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - tictactoe-network

networks:
  tictactoe-network:
    driver: bridge
